### ISSUE TITLE
Doesn't work for Pi4

### ISSUE THREAD

**Issue by dankozlowski** [MichaelS11/go-dht#3]
This lib appears to not work on Pi4.  I know that there is new BCM chip that changes some of the pin addressing.

**Comment by MichaelS11** [comment]
Ok, so might be a pin setup instead of a code issue?

**Comment by Dakuon** [comment]
Runs on Pi4 running Raspbian.
ReadRetry example with a AM2302 on GPIO4.

```
$ cat /proc/device-tree/model
Raspberry Pi 4 Model B Rev 1.2

$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

$ go version
go version go1.11.6 linux/arm

$ go run main.go
humidity: 16.5
temperature: 76.28
```

**Comment by MichaelS11** [comment]
@dankozlowski All good? If so, please close this issue.
