### ISSUE TITLE
Ubuntu Server 20.04.1 on Raspberry Pi 3B V2.1: "NewDHT error: pin out high error: sysfs-gpio (GPIO17): sysfs gpio is not initialized"

### ISSUE THREAD

**Issue by leviatan89** [MichaelS11/go-dht#4]
Hello!

I was trying to use [this tutorial](https://www.jeremymorgan.com/tutorials/go/get-temperature-raspberry-pi-go/) to read the temperature and humidity from Golang.

As said in the title I am using Ubuntu server 20.04 64bits. I have tested this on Ubuntu 20.10 also. Checked in all 64 and 32 bits editions.

The thermometer works on Raspbian just fine using this library but it doesn't on Ubuntu. This is the error:

```
NewDHT error: pin out high error: sysfs-gpio (GPIO17): sysfs gpio is not initialized
```

The thermometer model is `AOSONG AM2302`

Do you know how this could be fixed?

Thanks a lot!

**Comment by leviatan89** [comment]
Note: I also tried to use (this)[https://github.com/d2r2/go-dht] other library and failed.

**Comment by MichaelS11** [comment]
Did you try another guide? Like the one in the readme of this repository.

You could also try with Python for testing.

**Comment by leviatan89** [comment]
Hello! Sorry, I close this issue now. The problem is fixed running the Go program with sudo. Lol. I guess there must be a way for giving permision to my user to run GPIO but I haven't investigated futher.

Thanks for looking into this!
