### ISSUE TITLE
Low level duration too short

### ISSUE THREAD

**Issue by tomazbracic** [MichaelS11/go-dht#5]
Hi, 

I wanted to use your library for my DHT22 Sensor attached to RPi4, but I keep getting this kind of messages

```
Reader error: missing some readings - low level duration too short: 7.185µs
```

**Comment by MichaelS11** [comment]
Not sure how I can help or what you are asking. It is reporting an error with the readings it is seeing.

**Comment by MichaelS11** [comment]
Figured out? If so, please close this issue.
