### ISSUE TITLE
Facing download package incompatible imports

### ISSUE THREAD

**Issue by eltonlazzarin** [MichaelS11/go-dht#7]
Hi,
I am trying to download your package, but I am facing issues as shown bellow

go get github.com/MichaelS11/go-dht
go: downloading github.com/MichaelS11/go-dht v0.1.0
go: downloading periph.io/x/periph v3.7.0+incompatible
github.com/MichaelS11/go-dht imports
        periph.io/x/periph/conn/gpio: cannot find module providing package periph.io/x/periph/conn/gpio
github.com/MichaelS11/go-dht imports
        periph.io/x/periph/conn/gpio/gpioreg: cannot find module providing package periph.io/x/periph/conn/gpio/gpioreg
github.com/MichaelS11/go-dht imports

Using Raspberry Pie 3 on Raspberry Pi OS 64 bits

**Comment by MichaelS11** [comment]
Yeah, the imports could use an update. Welcome to make a pull request.

https://periph.io/news/2020/a_new_start/

**Comment by elazzarin** [comment]
Sorry, I did not understand what I need to do to fix those errors.

**Comment by VitorEstevam** [comment]
The code is updated but seems like a new release was not generate. @MichaelS11 can you generate a new release?

https://github.com/MichaelS11/go-dht/blob/337ec2bd007a55d6e97896ef36395c0d25c98b88/dht.go#L7

**Comment by MichaelS11** [comment]
New release has been created.

**Comment by VitorEstevam** [comment]
Did you publish the package on go pkg? Only v0.1.0 is available there to import using go get 

https://go.dev/doc/modules/publishing#:~:text=versioning%20workflow.-,Publishing%20steps,-Use%20the%20following

**Comment by MichaelS11** [comment]
My understanding is that it will update automatically. I am not aware of anyway to trigger it manually. Do you know how?

**Comment by VitorEstevam** [comment]
it seems to be working now. The auto-update aparently takes some time to run. The following link describes how to run manually if you need i the future. 

![image](https://user-images.githubusercontent.com/55667307/223223462-1c85dfab-55f9-4944-b7df-48235f711e9b.png)

https://go.dev/doc/modules/publishing#:~:text=versioning%20workflow.-,Publishing%20steps,-Use%20the%20following

Thanks for this, mate. Your fast support helped us a lot. ✅✅

**Comment by MichaelS11** [comment]
@eltonlazzarin Is it working for you now? Can this issue be closed?

**Comment by elazzarin** [comment]
Yes, it's working now! 

Thanks for helping.
